export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_PRODUCT_QTY = "ADJUST_PRODUCT_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_PRODUCT = "LOAD_CURRENT_PRODUCT";
export const LOAD_ALL_PRODUCTS = "LOAD_ALL_PRODUCTS";
export const UPDATE_CURRENT_PRODUCT = "UPDATE_CURRENT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
